### ISSUE TITLE
"Panic: send on closed channel" in websocket.go

### ISSUE THREAD

**Issue by mohamedeltawel** [enbility/ship-go#40]
This panic message appears sporadically in [websocket.go:261](https://github.com/enbility/ship-go/blob/5963bf4d9424d927b0e94f827bc43c276fe87d3e/ws/websocket.go#L261). The likely reason for this is that the web socket instance might be closed after the check at [line 257](https://github.com/enbility/ship-go/blob/5963bf4d9424d927b0e94f827bc43c276fe87d3e/ws/websocket.go#L257) and before the write channel is accessed for the read. The socket closing code block is not guarded against such a race condition.

**Comment by DerAndereAndi** [comment]
Hi, thanks for the notice. Would you have a stack trace of the panic I can look at? Without the possibility to reproduce it, I can hardly fix anything.

**Comment by mohamedeltawel** [comment]
Hello Andreas, This is the stack trace I've got when this issue appeared

```
panic: send on closed channel

goroutine 183 [running]:
github.com/enbility/ship-go/ws.(*WebsocketConnection).WriteMessageToWebsocketConnection(0xc0000c3400, {0xc0007b0f60, 0x2a, 0x30})
        github.com/enbility/ship-go@v0.6.0/ws/websocket.go:261 +0xfd
github.com/enbility/ship-go/ship.(*ShipConnection).sendShipModel(0xc0007931d0, 0x78?, {0xef9340?, 0xc00007d380?})
        github.com/enbility/ship-go@v0.6.0/ship/connection.go:380 +0x49
github.com/enbility/ship-go/ship.(*ShipConnection).handshakeHelloSend(0xc0007931d0, {0x1016ede, 0x7}, 0x0, 0x0)
        github.com/enbility/ship-go@v0.6.0/ship/hs_hello.go:257 +0xd5
github.com/enbility/ship-go/ship.(*ShipConnection).handshakeHello_Abort(0xc0007931d0)
        github.com/enbility/ship-go@v0.6.0/ship/hs_hello.go:89 +0x32
github.com/enbility/ship-go/ship.(*ShipConnection).handleState(0xc0007931d0, 0x0, {0x0, 0x0, 0x0})
        github.com/enbility/ship-go@v0.6.0/ship/handshake.go:152 +0x254
github.com/enbility/ship-go/ship.(*ShipConnection).setAndHandleState(0xc0007931d0, 0xc0007b0514?)
        github.com/enbility/ship-go@v0.6.0/ship/handshake.go:199 +0x2f
github.com/enbility/ship-go/ship.(*ShipConnection).handshakeHello_PendingInit(0xc0007931d0)
        github.com/enbility/ship-go@v0.6.0/ship/hs_hello.go:107 +0x7a
github.com/enbility/ship-go/ship.(*ShipConnection).handleState(0xc0007931d0, 0x0, {0x0, 0x0, 0x0})
        github.com/enbility/ship-go@v0.6.0/ship/handshake.go:143 +0x20f
github.com/enbility/ship-go/ship.(*ShipConnection).handleState(0xc0007931d0, 0x0, {0x0, 0x0, 0x0})
        github.com/enbility/ship-go@v0.6.0/ship/handshake.go:134 +0x1c9
github.com/enbility/ship-go/ship.(*ShipConnection).setAndHandleState(0xc0007931d0, 0x1a41d52?)
        github.com/enbility/ship-go@v0.6.0/ship/handshake.go:199 +0x2f
github.com/enbility/ship-go/ship.(*ShipConnection).handshakeInit_cmiStateServerWait(0xc0007931d0, {0xc000a91600, 0x2, 0x200})
        github.com/enbility/ship-go@v0.6.0/ship/hs_init.go:42 +0xa5
github.com/enbility/ship-go/ship.(*ShipConnection).handleState(0xc0007931d0, 0x0, {0xc000a91600, 0x2, 0x200})
        github.com/enbility/ship-go@v0.6.0/ship/handshake.go:117 +0xe5
github.com/enbility/ship-go/ship.(*ShipConnection).handleShipMessage(0xc000a91600?, 0x60?, {0xc000a91600?, 0xc000659ee8?, 0x1b000bd2ea8?})
        github.com/enbility/ship-go@v0.6.0/ship/handshake.go:44 +0x225
github.com/enbility/ship-go/ship.(*ShipConnection).HandleIncomingWebsocketMessage(0xc0007931d0, {0xc000a91600, 0x2, 0x200})
        github.com/enbility/ship-go@v0.6.0/ship/connection.go:245 +0x26f
github.com/enbility/ship-go/ws.(*WebsocketConnection).readShipPump(0xc0000c3400)
        github.com/enbility/ship-go@v0.6.0/ws/websocket.go:181 +0x127
created by github.com/enbility/ship-go/ws.(*WebsocketConnection).run in goroutine 228
        github.com/enbility/ship-go@v0.6.0/ws/websocket.go:86 +0xc5
```
