### ISSUE TITLE
Possible deadlock on WS close

### ISSUE THREAD

**Issue by mohamedeltawel** [enbility/ship-go#42]
My application involves creating multiple SHIP devices and repeatedly starting/stopping the service. Every now and then, when I close the service, the application gets stuck. when replacing all sync.Mutex with deadlock.Mutex in websocket.go, the following trace logs appear:
```
POTENTIAL DEADLOCK:
Previous place where the lock was grabbed
goroutine 22687 lock 0xc0069cb758
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ws\websocket.go:256 ws.(*WebsocketConnection).WriteMessageToWebsocketConnection { w.muxShipWrite.Lock() } <<<<<
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ws\websocket.go:255 ws.(*WebsocketConnection).WriteMessageToWebsocketConnection { func (w *WebsocketConnection) WriteMessageToWebsocketConnection(message []byte) error { }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ship\connection.go:380 ship.(*ShipConnection).sendShipModel { err = c.dataWriter.WriteMessageToWebsocketConnection(shipMsg) }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ship\hs_hello.go:256 ship.(*ShipConnection).handshakeHelloSend {  }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ship\hs_hello.go:88 ship.(*ShipConnection).handshakeHello_Abort {  }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ship\handshake.go:151 ship.(*ShipConnection).handleState { case model.SmeHelloStateAbort: }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ship\handshake.go:199 ship.(*ShipConnection).setAndHandleState { c.handleState(false, nil) }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ship\hs_hello.go:108 ship.(*ShipConnection).handshakeHello_PendingInit { } }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ship\handshake.go:142 ship.(*ShipConnection).handleState { case model.SmeHelloStatePendingInit: }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ship\handshake.go:133 ship.(*ShipConnection).handleState { } }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ship\handshake.go:199 ship.(*ShipConnection).setAndHandleState { c.handleState(false, nil) }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ship\hs_init.go:42 ship.(*ShipConnection).handshakeInit_cmiStateServerWait { c.setAndHandleState(model.SmeHelloState) }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ship\handshake.go:116 ship.(*ShipConnection).handleState { } }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ship\handshake.go:44 ship.(*ShipConnection).handleShipMessage { c.handleState(timeout, message) }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ship\connection.go:245 ship.(*ShipConnection).HandleIncomingWebsocketMessage { c.handleShipMessage(false, message) }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ws\websocket.go:157 ws.(*WebsocketConnection).readShipPump { select { }

Have been trying to lock it again for more than 30s
goroutine 22688 lock 0xc0069cb758
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ws\websocket.go:327 ws.(*WebsocketConnection).closeShipWriteChannel { w.muxShipWrite.Lock() } <<<<<
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ws\websocket.go:326 ws.(*WebsocketConnection).closeShipWriteChannel { func (w *WebsocketConnection) closeShipWriteChannel() { }      
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ws\websocket.go:97 ws.(*WebsocketConnection).writeShipPump.func1 { /*go*/ w.closeShipWriteChannel() }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ws\websocket.go:106 ws.(*WebsocketConnection).writeShipPump { if w.isConnClosed() { }

Here is what goroutine 22687 doing now
goroutine 22687 [chan send]:
github.com/enbility/ship-go/ws.(*WebsocketConnection).WriteMessageToWebsocketConnection(0xc0069cb700, {0xc004164c30, 0x2a, 0x30})
        C:/Users/mohamed.eltawel/go/pkg/mod/github.com/enbility/ship-go@v0.6.0/ws/websocket.go:263 +0x10b
github.com/enbility/ship-go/ship.(*ShipConnection).sendShipModel(0xc006139b30, 0x78?, {0x1328c00?, 0xc0012beb20?})
        C:/Users/mohamed.eltawel/go/pkg/mod/github.com/enbility/ship-go@v0.6.0/ship/connection.go:380 +0x49
github.com/enbility/ship-go/ship.(*ShipConnection).handshakeHelloSend(0xc006139b30, {0x144aff4, 0x7}, 0x0, 0x0)
        C:/Users/mohamed.eltawel/go/pkg/mod/github.com/enbility/ship-go@v0.6.0/ship/hs_hello.go:257 +0xd5
github.com/enbility/ship-go/ship.(*ShipConnection).handshakeHello_Abort(0xc006139b30)
        C:/Users/mohamed.eltawel/go/pkg/mod/github.com/enbility/ship-go@v0.6.0/ship/hs_hello.go:89 +0x32
github.com/enbility/ship-go/ship.(*ShipConnection).handleState(0xc006139b30, 0x0, {0x0, 0x0, 0x0})
        C:/Users/mohamed.eltawel/go/pkg/mod/github.com/enbility/ship-go@v0.6.0/ship/handshake.go:152 +0x254
github.com/enbility/ship-go/ship.(*ShipConnection).setAndHandleState(0xc006139b30, 0xc000fa1860?)
        C:/Users/mohamed.eltawel/go/pkg/mod/github.com/enbility/ship-go@v0.6.0/ship/handshake.go:199 +0x2f
github.com/enbility/ship-go/ship.(*ShipConnection).handshakeHello_PendingInit(0xc006139b30)
        C:/Users/mohamed.eltawel/go/pkg/mod/github.com/enbility/ship-go@v0.6.0/ship/hs_hello.go:107 +0x7a
github.com/enbility/ship-go/ship.(*ShipConnection).handleState(0xc006139b30, 0x0, {0x0, 0x0, 0x0})
        C:/Users/mohamed.eltawel/go/pkg/mod/github.com/enbility/ship-go@v0.6.0/ship/handshake.go:143 +0x20f
github.com/enbility/ship-go/ship.(*ShipConnection).handleState(0xc006139b30, 0x0, {0x0, 0x0, 0x0})
        C:/Users/mohamed.eltawel/go/pkg/mod/github.com/enbility/ship-go@v0.6.0/ship/handshake.go:134 +0x1c9
github.com/enbility/ship-go/ship.(*ShipConnection).setAndHandleState(0xc006139b30, 0x1f935f2?)
        C:/Users/mohamed.eltawel/go/pkg/mod/github.com/enbility/ship-go@v0.6.0/ship/handshake.go:199 +0x2f
github.com/enbility/ship-go/ship.(*ShipConnection).handshakeInit_cmiStateServerWait(0xc006139b30, {0xc0026d3e00, 0x2, 0x200})
        C:/Users/mohamed.eltawel/go/pkg/mod/github.com/enbility/ship-go@v0.6.0/ship/hs_init.go:42 +0xa5
github.com/enbility/ship-go/ship.(*ShipConnection).handleState(0xc006139b30, 0x0, {0xc0026d3e00, 0x2, 0x200})
        C:/Users/mohamed.eltawel/go/pkg/mod/github.com/enbility/ship-go@v0.6.0/ship/handshake.go:117 +0xe5
github.com/enbility/ship-go/ship.(*ShipConnection).handleShipMessage(0xc0026d3e00?, 0xb0?, {0xc0026d3e00?, 0xc000bb7ee8?, 0x28e33842ea8?})
        C:/Users/mohamed.eltawel/go/pkg/mod/github.com/enbility/ship-go@v0.6.0/ship/handshake.go:44 +0x225
github.com/enbility/ship-go/ship.(*ShipConnection).HandleIncomingWebsocketMessage(0xc006139b30, {0xc0026d3e00, 0x2, 0x200})
        C:/Users/mohamed.eltawel/go/pkg/mod/github.com/enbility/ship-go@v0.6.0/ship/connection.go:245 +0x26f
github.com/enbility/ship-go/ws.(*WebsocketConnection).readShipPump(0xc0069cb700)
        C:/Users/mohamed.eltawel/go/pkg/mod/github.com/enbility/ship-go@v0.6.0/ws/websocket.go:183 +0x127
created by github.com/enbility/ship-go/ws.(*WebsocketConnection).run in goroutine 23442
        C:/Users/mohamed.eltawel/go/pkg/mod/github.com/enbility/ship-go@v0.6.0/ws/websocket.go:88 +0xc5
Other goroutines holding locks:
goroutine 114 lock 0xc001ab73d8
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ws\websocket.go:256 ws.(*WebsocketConnection).WriteMessageToWebsocketConnection { w.muxShipWrite.Lock() } <<<<<
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ws\websocket.go:255 ws.(*WebsocketConnection).WriteMessageToWebsocketConnection { func (w *WebsocketConnection) WriteMessageToWebsocketConnection(message []byte) error { }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ship\connection.go:380 ship.(*ShipConnection).sendShipModel { err = c.dataWriter.WriteMessageToWebsocketConnection(shipMsg) }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ship\connection.go:174 ship.(*ShipConnection).CloseConnection.func1 {  }
C:/Program Files/Go/src/sync/once.go:74 sync.(*Once).doSlow { if o.done.Load() == 0 { }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ship\connection.go:193 ship.(*ShipConnection).CloseConnection { }) }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\ship\connection.go:151 ship.(*ShipConnection).CloseConnection { func (c *ShipConnection) CloseConnection(safe bool, code int, reason string) { }
..\..\..\go\pkg\mod\github.com\enbility\ship-go@v0.6.0\hub\hub_pairing.go:150 hub.(*Hub).DisconnectSKI { con.CloseConnection(true, 0, reason) }
internal\energyguard.go:617 internal.(*EnergyGuard).UnregisterRemoteSKI { h.myService.DisconnectSKI(remoteSki, "Disconnected by CEM") }
internal\energyguard.go:616 internal.(*EnergyGuard).UnregisterRemoteSKI { defer h.mu.Unlock() }
cmd\eebus-hub\cemApi.go:677 main.init.func25 { // }) }
internal\restHandler.go:91 internal.(*RestHandler).PushRoutes.func1 { // Insert endpoint to the group handler }
..\..\..\go\pkg\mod\github.com\gin-gonic\gin@v1.10.0\context.go:185 gin.(*Context).Next { c.handlers[c.index](c) }
..\..\..\go\pkg\mod\github.com\gin-gonic\gin@v1.10.0\context.go:182 gin.(*Context).Next { func (c *Context) Next() { }
..\..\..\go\pkg\mod\github.com\gin-gonic\gin@v1.10.0\context.go:185 gin.(*Context).Next { c.handlers[c.index](c) }
..\..\..\go\pkg\mod\github.com\gin-gonic\gin@v1.10.0\context.go:182 gin.(*Context).Next { func (c *Context) Next() { }
..\..\..\go\pkg\mod\github.com\gin-gonic\gin@v1.10.0\gin.go:590 gin.(*Engine).ServeHTTP {  }
C:/Program Files/Go/src/net/http/server.go:3210 http.serverHandler.ServeHTTP { handler.ServeHTTP(rw, req) }
C:/Program Files/Go/src/net/http/server.go:2092 http.(*conn).serve { serverHandler{c.server}.ServeHTTP(w, w.req) }
```
Note: code lines are shifted by one line

The possible reason for this problem is that the function WriteMessageToWebsocketConnection is blocked in [Line 261](https://github.com/enbility/ship-go/blob/69e26eb81a7723defa5a525a5a5552566bf7d333/ws/websocket.go#L261) waiting for the channel to be emptied, and the[ Line of code](https://github.com/enbility/ship-go/blob/69e26eb81a7723defa5a525a5a5552566bf7d333/ws/websocket.go#L103) which is supposed to consume the channel is never called upon closing the channel.

**Comment by DerAndereAndi** [comment]
Thanks a lot for the bug report!

Would you be interested in providing a unit test that shows the issue? As an idea: It doesn't have to happen every time in the test, but a at least 1 out of 10 would be great and then make the test run at least 10 times.
